# Generated by Django 5.0.3 on 2024-03-23 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='menbers',
            new_name='members',
        ),
    ]
